language: node_js
node_js:
- "6.10"

deploy:
  provider: lambda
  function_name: billing-report
  region: ap-northeast-1
  role: arn:aws:iam::907331964011:role/TravisLambdaDeploy
  runtime: nodejs6.10
  handler_name: handler
  access_key_id:
    secure: bwQwm2v2YgBV3BIs40d0uZpLxFf0AD/BlnyMkCJB5YbZifuyIytVsdm14HKPPRL20iCoML4WSbX+aPN7tgNaDraaq8DRpkuOyCo//aFJL9HZ0QFa6dhbhOxWZGlwWg9NIcAV47Ugj+GmNYg3kzixF9W4B2S17kIeZV636uHD/L8LPKlz22zhnNvoyAvRxw1rL9/SdKCBoIdb0DfYFjGpqlWJ9y3OiSZVhkep7CHuwurbBsDlYo1l8vb9Ruty3XZMVmtRpTOQdJKD/5cX6GH0eVgPAlaamEQt/vMuA3kYUp5xTnYc7cknAAD7MIW2JNlycovbN49YE5annyqoMvbOtrlUpD57EUKakn79oUk10ZLD0obCRzIjDHpErF2y1/zlUx5vKc+VKdPXJA0AfFn/CTr+FEzeTJmfuLhfc0M3HjI1fEVsct6G9eDrPH8+syEoSsh+Fq9HwCuAIy0/7YRWjClO9ueM6HQ+6o+1a6J1b26FiD0qXzhcv9X5VWzE8sQw/3ycAWtkzYTgKeymTbnZRFV33flrEFfxzpSTE6tRcN9PmywYodznI3YzvNn3N/8/URsAhJvO0szUSskfhDxR5jEVefPxSMV7+3h5dMbxzhPJKfQGfrd3izGElpfv1cGUTrO5dTbtf4FxoA+M5xyOa98PYPwLDzYMOjs99Bd7BAU=
  secret_access_key:
    secure: r9tqdluYbPgEeLbO3WL3BQOLopGtmaNWoDMkU+1LCZa9edfv2IXpfbxl+YJy9SV1hn0DWsCp9X0KuT7Sgy+0pip4lHyCh24ZeQnFmpJsPw35I4K21Y/47H3k8IcxCeQpR3U3y0MMwfPBDdXWAioP5NVSNCkyNenGtPGg4JwKe7N1lU4Fpn2StBA/vinmQHPQcmNO/B95DpbqZXVS4ZBBJT1VnQVKUthM6FHhocwN7RlAyjcZ0N3riaP0tiuV+AkuHYP/MTtn/9+k96TAgUfRKelPm4BsXRs0JSGzpgJjcYBUkv3UgIAdpc17EAmLJeJQKU0yAg7H11Bz0NJ7iQ0TjVMFAECu5lUIE0YzviXYcEulUsjii6phyIzw544JJ5mlJf6tqZpraFBazRyjXSDwYOg8B3lOp9s4OcjpIrKfwjckhltiGF07Kqr0vgzpS64eBXH0D8ArC0pKlSVwjxOJMD7JrzzoWD8wnXIU7Tq/PeJVGSSKpMB1Fm6RaO3PUhdTwo8mDm5Yxd1upoYCeEOy6VEz3Jt8R88pxqdRDpOafDW2tphEoWhwvA6vZJdpvtqEQRQpRluiwv9Vb2f9To7RBTSJG37rsgEYoQuyxzOa6oMFZvJBXV1/GmnVMckaZb1k1BT/EshqwRwbw6zTUXHaEFFsg+RnI6xGibYoU/IlVdk=
